<h3 class="attending-title">Attending</h3>
	<?php
    $attendingList = $this->event->getMembers();
    foreach($attendingList as $user){
			$eid = $this->event->getEid();
            $uid = $user->getUid();
    ?>
			<div class="attending-item attending-item-<?= $uid ?>">
			<a href='/profile/public/uid/<?= $user->getUid() ?>'>
            <img src='/img/profile-pic/uid/<?= $user->getUid() ?>' height=100  width=100/></a>
			<div class='attending-details'><a href='/profile/public/uid/<?= $user->getUid() ?>'><?= $user->getFirstName() ?> <?= substr($user->getLastName(),0,1) . "."?></a></div>       			
            
	</div>
	<?php } ?>
	<? if (!($this->indexCreator || $this->indexMember) && !$this->didRequest) {
	?>
			    <!--<a href = '/event/request/eid/<?= $this->eid; ?>'><img class="attend-button" style ="background: url('/img/profile-pic/uid/<?=$this->curUser->getUid()?>'); background-size: 85px 85px" src="/images/attend-hover.png" height=85px  width=85px/></a>-->
		    <a class='attend-button' href = '/event/request/eid/<?= $this->eid; ?>'><img src='/img/profile-pic/uid/<?= $this->curUser->getUid() ?>' height=100  width=100/></a></a>
	<? }?>
</div>
<div class = "attending-list-ajax" style='display:none'>
    <div class="attending-item attending-item-<?= $uid ?>">
		    <a href='/profile/public/uid/<?= $user->getUid() ?>'>
	            <img src='/img/profile-pic/uid/<?= $user->getUid() ?>' height=100  width=100/></a>
            <?php if ($this->indexCreator || $this->indexMember) { ?>
		    <div class='attending-details'></div>
            <?php } ?>        			
    </div>
    
</div>
