<h3 class="attending-title">Attending</h3>
	<?php 
    $attendingList = $this->event->getMembers();
    foreach($attendingList as $user){
			$eid = $this->event->getEid();
            $uid = $user->getUid();
    ?>
	<div class="attending-item attending-item-<?= $uid ?>">
	    <a class='friend-tooltip'  href='/profile/public/uid/<?= $user->getUid() ?>'>
		<img src='<?= Application_Model_Utils_ImageUtil::getProfilePicURL($user) ?>' height=70  width=70/>
		<span class='friend-tooltip-name'><?= $user->getFirstName() ?> <?= substr($user->getLastName(),0,1) ?>.</span>
	    </a>			  
	</div>
	<?php } ?>
	<? if(!$this->isEventExpired) {
	    if (!($this->indexCreator || $this->indexMember) && !$this->didRequest) {
	?>
			    <a class='attend-button' style="background: url('<?=Application_Model_Utils_ImageUtil::getProfilePicURL($this->curUser)?>') no-repeat center center; background-size: 70px 70px" href = '/event/request/eid/<?= $this->eid; ?>'>

					<img class="attend-img"  src="/images/attend-hover.png" height="70px"  width="70px" />
				</a>
			  
		  <!-- <a class='attend-button' href = '/event/request/eid/<?= $this->eid; ?>'><img src='/img/profile-pic/uid/<?= $this->curUser->getUid() ?>' height=100  width=100/></a></a>-->
	<? 		}
		
		}
		else {
			echo "<h3 class='event-ended'>This event has already ended.</h2>";

		}
		?>

<div class="attending-list-ajax" style='display: none'>
    <div class="attending-item attending-item-<?= $uid ?>">
		    <a href='/profile/public/uid/<?= $user->getUid() ?>'>
	            <img src='<?= Application_Model_Utils_ImageUtil::getProfilePicURL($user)?>' height=70  width=70/>
		    </a>
            <?php if ($this->indexCreator || $this->indexMember) { ?>
		    <div class='attending-details'></div>
            <?php } ?>        			
    </div> 
</div>
