<div id="view-content">
    <div class="view-wrapped">	 
        <div class="event_main">
            <div class="event_right">
                <div class="event-header">
                    <h1 class="event_title"><?php if($this->event->getCreator()->getEmail() == $this->identity) {
                echo $this->event->getCreator()->getFirstName(). " " .substr($this->event->getCreator()->getLastName(),0,1)."."." wants to " .$this->event->getShortDescription();
                } else {    
                echo $this->event->getCreator()->getFirstName(). " " .substr($this->event->getCreator()->getLastName(),0,1)."."." wants to " .$this->event->getShortDescription();
                }
                    ?></h1>
                </div>
                <div class="event-detail-wrapper">
                    <div class='event_date'>
                        <h4><?= date('F j\, Y',$this->event->getDate()->getTimestamp()); ?></h4>
                    </div>
                    <div class='event_place'>
                        <h4><?= $this->event->getLocation() ?> </h4>
                    </div>
                    <div class="event_location">
                        <? if($this->event->getLongDescription()){?>
                        <h4><?= $this->event->getLongDescription() ?></h4>
                        <? } ?>
                    </div>
                </div>
                    <div class ="event_wall">
                        <h3 class="wall_title">Wall</h3>
                        <div id="posts">
                        </div>
                        <?= $this->DisplayEventWall($this->event,$this->identity) ?>
                    </div>
                    <div class="ajax_template" style="display:none">
                        <?= $this->partial('wall_post.phtml') ?>
                    </div>
            </div>
            <div class="event-left">
                <div class="event_img">
                 <img src="<?= Application_Model_Utils_ImageUtil::getProfilePicURL($this->event->getCreator()) ?>" height=150  width=150/>
                </div>
                <div class="event_self">
                            <?php if ($this->event->getCreator()->getEmail() == $this->identity) {
                echo "<h4>You own this event.</h4>";
            } else {
                echo "<h4>You're going to this event.</h4>";
            } ?>
                </div>
                <?= $this->partial('attendingList.phtml',array('event'=>$this->event,'identity'=>$this->identity, 'indexCreator'=>$this->indexCreator, 'isEventExpired'=>$this->isEventExpired, 'didRequest'=>$this->didRequest, 'curUser'=>$this->curUser)); ?>
                <? if ($this->indexCreator) { ?>
                <div class="interested-list"><?= $this->DisplayInterestedList($this->event) ?></div>
                <? } ?>
            </div>
        </div>
