<div id="view-content">
    <div class="view-wrapped">	 
        <div class="event_main">
            <h2 class="event_title"><?= $this->event->getCreator()->getFirstName()." wants to ".$this->event->getShortDescription() ?></h2>
            <div class="event_img">
                 <img src="/img/profile-pic/uid/<?=$this->identity ?>" height=180  width=180/>
            </div>
            <div class="event_right">
            <div class='event_date'>
                <h4><?= date('F j\, Y',$this->event->getDate()->getTimestamp()); ?></h4>
            </div>
             <div class='event_place'>
                <h4><?= $this->event->getLocation() ?> </h4>
                
            </div>
                <div class="event_location">
                    <h4><?= $this->event->getLongDescription() ?></h4>
                </div>
            </div>
            <div class="event_self">Event Member</div>
        </div>