		  <div class="tags_area">

		 	 <div class="tags_base">
				<? if(count($this->tagArray) > 0){ 
						foreach($this->tagArray as $tag){ 		
							if(!$this->interestModel->interest->state[$tag->getTagName()]){
								$toggle = 'tag_disable';
								$toggleArrow = 'tag-arrow-color';
							}
							else {
								$toggle = '';
								$toggleArrow = '';
							}
						?>
							<? if($this->isOwn) {?>
							       <div class ="tags <?=$toggle ?>" id="tag_<?=str_replace(' ','_',$tag->getTagName());?>" onclick = 'Tags.toggleTag("tag_<?=str_replace(' ','_',$tag->getTagName());?>")'>
								       <div class="tag_text"><?=$tag->getTagName()?></div>
									     <div class="close_tag" onclick="Tags.removeTag('tag_<?=str_replace(' ','_',$tag->getTagName());?>')"></div>
							       <div class="tags-arrow <?=$toggleArrow ?>"></div></div>
						 	<?}else{?>
							       <div class ="tags " id="tag_<?=str_replace(' ','_',$tag->getTagName());?>">
								       <div class="tag_text">
										  <?=$tag->getTagName()?>
									   </div>
									   <div class="tags-arrow"></div>
								   </div>
							<?}?>
					
							
				<? 			
						}		
				}
				else
				{
				  echo "<h3>No Tags Available</h3>";  
				}
				?>		  
		  	</div>
		  </div>