<?php $auth = Zend_Auth::getInstance();
        if(!$auth->hasIdentity()){ ?>

<div class="privacy-logo"><h1 class="thelogo"><a class="logo" href="<?= $this->url(array('controller'=>'index','action'=>'index'));?>">PlumeType</a></h1><h1 class="questionmark">privacy policy</h1></div>

<?php } else { ?>
<h1 class="cms-title">Privacy</h1>
<?php } ?>
    <?= $this->Errors($this->errors); ?>
    <p>
        <?=$this->DisplayFlashMessages($this->flashMessages); ?>
    </p>
    
   
    <div class="cms-text" style="margin-bottom: 60px;">
    <p>(You = the user, We = PlumeType)
<br/>
<p>We collect all data input onto the site. This includes: any personal information you choose to share, your tags and any text written. </p>
<br />
<p>We may also read any messages you share with other users on the site (both publicly and privately) for security reasons only (e.g. to stop spam or phishing attempts).</p>
<br />
<p>Data will be collected for statistical tracking purposes; feedback to help with the site's development; and personalized deals or advertisements in order to increase our users' experience with the site. 
</p><br />
<p>Data may also be shared with third parties only after you have explicitly allowed for it. This will be done, again, in order to enhance your experience with the site. More details will be given later.
</p><br/>
<p>You assume all responsibility for any loss of privacy or other harm resulting from your voluntary disclosure of personal information. We urge you to exercise caution and judgment when disclosing any personal information.
</p><br />
This policy will be updated periodically as more features are implemented. If you have any questions or suggestions, please use our contact page to get in touch with us.</p>
    </div>
<style type="text/css">
    .right-block {display: none;}
    
</style>