<form id = "<?=$this->element->getName(); ?>" action = "<?= $this->element->getAction(); ?>" 
	method = "<?=$this->element->getMethod() ?>">
    
      <h1>Change your password</h1>
    	<ul>
            <li class="reglist"><?= $this->element->originalPassword; ?></li>
			<li class="reglist"><?= $this->element->password; ?></li>
			<li class="reglist"><?= $this->element->password2; ?></li>
            <?= $this->element->submit; ?>
        </ul>         
</form>