<form id = "<?=$this->element->getName(); ?>" action = "<?= $this->element->getAction(); ?>" 
	method = "<?=$this->element->getMethod() ?>">

<ul class="centerform">

	<li class="email"><?= $this->element->email_input; ?></li>
	<li class="password"><?= $this->element->password_input; ?></li>
</ul>
        <div class="button">
            <div class="inner_button">
            <?= $this->element->login; ?>
               
            </div>
            </div>

</form>
