<form id = "<?=$this->element->getName(); ?>" action = "<?= $this->element->getAction(); ?>" 
      method = "<?=$this->element->getMethod() ?>">
<br/>
    <ul class="centerform">
        
	<li class="email"><?= $this->element->email; ?></li>
	<li class=""><?= $this->element->name; ?></li>
        <li class=""><?= $this->element->subject; ?></li>
    <li class=""><?= $this->element->text; ?></li>
        <div class="button">
            <div class="inner_button">
                <?= $this->element->contact_submit; ?>
                </div>
            </div>
    </ul>
</form>