<form id = "<?=$this->element->getName(); ?>" action = "<?= $this->element->getAction(); ?>" 
	method = "<?=$this->element->getMethod() ?>">


<ul class="centerform">
  
	<li class="reglist"><?= $this->element->firstName; ?></li>
	<li class="reglist"><?= $this->element->lastName; ?></li>
	<li class="reglist"><?= $this->element->city; ?></li>
        <div class="button">
            <div class="inner_button">
                <?= $this->element->submit; ?> 
                </div>
            </div>
	
</ul>
</form>