<form id = "<?=$this->element->getName(); ?>" action = "<?= $this->element->getAction(); ?>" 
	method = "<?=$this->element->getMethod() ?>">
<script type="text/javascript">

</script>
<ul id="registration">
	<li class="reglist"><dt class="form_text"><label for="email" class="required">Email:</label></dt><dd class="form_element"><?= $this->element->email; ?></dd></li>
	<li class="reglist"><dt  class="form_text"><label for="firstName" class="required">First Name:</label></dt><dd class="form_element"><?= $this->element->firstName; ?></dd></li>
	<li class="reglist"><dt  class="form_text"><label for="lastName" class="required">Last Name:</label></dt><dd class="form_element"><?= $this->element->lastName; ?></dd></li>
	<li class="reglist"><dt  class="form_text"><label for="city" class="required">City:</label></dt><dd class="form_element"><?= $this->element->city; ?></dd></li>
	<li class="reglist"><dt  class="form_text"><label for="gender">Gender:</label></dt><div class="form_element"><?= $this->element->gender; ?></dd></li>
	<li class="reglist"><dt  class="form_text"><label for="password" class="required">Password:</label></dt><dd class="form_element"><?= $this->element->password; ?></dd></li>
	<li class="reglist"><dt  class="form_text"><label for="password2" class="required">Password Again:</label></dt><dd class="form_element"><?= $this->element->password2; ?></dd></li>
	<li class="reglist"><dt  class="form_submit"><?= $this->element->register; ?> or <a href ="<?= $this->url(array('controller'=>'index','action'=>'index'));?>">Login</a></dd></li>
</ul>
        </form>