<form id = "<?=$this->element->getName(); ?>" action = "<?= $this->element->getAction(); ?>" 
	method = "<?=$this->element->getMethod() ?>">


  <h1>Edit your account</h1>
	<li class="reglist"><?= $this->element->firstName; ?></li>
	<li class="reglist"><?= $this->element->lastName; ?></li>
	<li class="reglist"><?= $this->element->city; ?></li>
    <li class="reglist"><?= $this->element->gender; ?></li>
    <li class="reglist">Receive email notifications <?= $this->element->hasEmailPerm; ?></li>
        <span class="edit-140char">Tell everyone about yourself in 140 characters</span>
        <li class="reglist"><?= $this->element->description;?></li>
                <?= $this->element->submit; ?> 
                
</form>