<form id = "<?=$this->element->getName(); ?>" action = "<?= $this->element->getAction(); ?>" 
	method = "<?=$this->element->getMethod() ?>">

<h1>Register</h1>
<ul id="registration">
  
	<li class="reglist"><dt class="form_text float_left"><label for="email" class="required">Email:</label></dt><dd class="form_element"><?= $this->element->email; ?></dd></li>
	<li class="reglist"><dt  class="form_text float_left"><label for="firstName" class="required">First Name:</label></dt><dd class="form_element"><?= $this->element->firstName; ?></dd></li>
	<li class="reglist"><dt  class="form_text float_left"><label for="lastName" class="required">Last Name:</label></dt><dd class="form_element"><?= $this->element->lastName; ?></dd></li>
	<li class="reglist"><dt  class="form_text float_left"><label for="city" class="required">City:</label></dt><dd class="form_element"><?= $this->element->city; ?></dd></li>
	<li class="reglist"><dt  class="form_text float_left"><label for="gender">Gender:</label></dt><div class="form_element"><?= $this->element->gender; ?></dd></li>
	<li class="reglist"><dt  class="form_text float_left"><label for="password" class="required">Password:</label></dt><dd class="form_element"><?= $this->element->password; ?></dd></li>
	<li class="reglist"><dt  class="form_text float_left"><label for="password2" class="required">Password Again:</label></dt><dd class="form_element"><?= $this->element->password2; ?></dd></li>
	<li class="reglist"><dt  class="form_submit"><?= $this->element->register; ?></dd></li>
</ul>
        </form>