	<form id = "<?=$this->element->getName(); ?>" action = <?=$this->element->getAction(); ?>
	method = "<?=$this->element->getMethod() ?>">

        <div class="friend_finder_inner">
        
            <div class="search_friend_form"><?= $this->element->profileSearch_field; ?></div>
	
            <div class="search_friend_submit"><?= $this->element->search; ?></div>
        </div>
      <div class="icon_bar">
            <ul>
                <li class="friends-button">
                  <a href="<?= $this->url(array('controller'=>'event-list','action'=>'index')) ?>">
                      <img height="50" src="<?= $this->baseUrl('images/settings.png') ?>" /></a>
                </li>
                <li class="friends-button">
                  <a href="<?= $this->url(array('controller'=>'notification','action'=>'index')) ?>">
                      <img height="50" src="<?= $this->baseUrl('images/settings.png') ?>" /></a>
                </li>
                 <li class="settings-button">
                  
                     <img height="50" src="<?= $this->baseUrl('images/settings.png') ?>" />
                     
                     <ul class="sub-settings">
                         <li class="first-setting"><a href="<?= $this->url(array('controller'=>'account-edit','action'=>'index')) ?>">Edit Account Info</a></li>
                         <li class="last-setting"><a href="<?= $this->url(array('controller'=>'index','action'=>'logout')) ?>">Logout</a></li>
                     </ul>
                 </li>
            </ul>
	
        </div>    
        <div class="form_submit"><?= $this->element->hidden_formName; ?> </div>
        
</form>
<script type = 'text/javascript'>
		$('#profileSearch #search').click(function(event){
			if($('#profileSearch #profileSearch_field').val().length == 0)
				event.preventDefault();
		 });
</script>