	<form id = "<?=$this->element->getName(); ?>" action = <?=$this->element->getAction(); ?>
	method = "<?=$this->element->getMethod() ?>">

        <div class="friend_finder_inner">
        
            <div class="search_friend_form"><?= $this->element->profileSearch_field; ?></div>
	
            <div class="search_friend_submit"><?= $this->element->search; ?></div>
        </div>
      <div class="icon_bar">
            <ul class="top-bar">
                <li class="friends-button">
                  
                      <img height="40" src="<?= $this->baseUrl('images/friends-icon.png') ?>" />
					  
					  <ul class="sub-setting2">
						<?php $auth = Application_Model_UserSettings::hasIdentity();
					
						if($auth){ 
                    	$this->identity = $auth; ?>
						
						<?$this->DisplayPendingRequests($this->identity); ?>
						<?php } ?>
					  
					  </ul>
                </li>
                <li class="notifications-button">
                  <a href="<?= $this->url(array('controller'=>'notification','action'=>'index'), null, true) ?>">
                      <img height="40" src="<?= $this->baseUrl('images/notifications-icon.png') ?>" title="Notifications"/></a>
                </li>
                 <li class="settings-button">
                  
                     <img height="40" src="<?= $this->baseUrl('images/settings.png') ?>" title="Settings"/>
                   
                     <ul class="sub-settings">
                         <li class="first-setting"><a href="<?= $this->url(array('controller'=>'account-edit','action'=>'index'), null, true) ?>">Edit Account Info</a></li>
                         <li class="last-setting"><a onclick = "Login.logout()"/>Logout</a></li>
                     </ul>
                 </li>
            </ul>
	
        </div>    
        <div class="form_submit"><?= $this->element->hidden_formName; ?> </div>
        
</form>
<script type = 'text/javascript'>
		$('#profileSearch #search').click(function(event){
			if($('#profileSearch #profileSearch_field').val().length == 0)
				event.preventDefault();
		 });
</script>