<form id = "<?=$this->element->getName(); ?>" action = "<?= $this->element->getAction(); ?>" 
	method = "<?=$this->element->getMethod() ?>">

<h1>Quick Start</h1>
<ul id="generic_form">
    <li class=""><dt class=""><label for="musictype" class="required">My favorite type(s) of music</label></dt><dd class="form_element"><?= $this->element->musictype; ?></dd></li>
    <li class=""><dt class=""><label for="artists" class="required">My favorite artists/bands are</label></dt><dd class="form_element"><?= $this->element->artists; ?></dd></li>
    <li class=""><dt class=""><label for="filmgenre" class="required">My favorite film genre(s)</label></dt><dd class="form_element"><?= $this->element->filmgenre; ?></dd></li>
    <li class=""><dt class=""><label for="films" class="required">My favorite films are</label></dt><dd class="form_element"><?= $this->element->films; ?></dd></li>
    <li class=""><dt class=""><label for="hangout" class="required">Where do you like to hang out on a typical weekday?</label></dt><dd class="form_element"><?= $this->element->hangout; ?></dd></li>
   
    <li class=""><dt class=""><label for="hobbies" class="required">My hobbies are</label></dt><dd class="form_element"><?= $this->element->hobbies; ?></dd></li>
    <li class=""><dt class=""><label for="friday" class="required">It's Friday night. Where are you hanging out?</label></dt><dd class="form_element"><?= $this->element->friday; ?></dd></li> 
    <li class=""><dt class=""><label for="boardgames" class="required">Play any tabletop games</label></dt><dd class="form_element"><?= $this->element->boardgames; ?></dd></li>
    <li class=""><dt class=""><label for="books" class="required">My favorite type of books are</label></dt><dd class="form_element"><?= $this->element->books; ?></dd></li>
    <li class=""><dt class=""><label for="bookswriters" class="required">My favorite books and/or writers are</label></dt><dd class="form_element"><?= $this->element->bookswriters; ?></dd></li>
    
    <li class=""><dt class=""><label for="news" class="required">What kind of news do you like to follow?</label></dt><dd class="form_element"><?= $this->element->news; ?></dd></li>
    <li class=""><dt class=""><label for="cuisine" class="required">What type of cuisine do you like?</label></dt><dd class="form_element"><?= $this->element->cuisine; ?></dd></li>
    <li class=""><dt class=""><label for="inorout" class="required">Indoors or Outdoors</label></dt><dd class="form_element"><?= $this->element->inorout; ?></dd></li>
    <li class=""><dt class=""><label for="sports" class="required">What kind of sports do you like doing?</label></dt><dd class="form_element"><?= $this->element->sports; ?></dd></li>
    <li class=""><dt class=""><label for="teams" class="required">Favorite sports teams?</label></dt><dd class="form_element"><?= $this->element->teams; ?></dd></li>
    
    <li class=""><dt class=""><label for="videogames" class="required">Play any video games?</label></dt><dd class="form_element"><?= $this->element->videogames; ?></dd></li>
    <li class=""><dt class=""><label for="brands" class="required">Favorite Brands</label></dt><dd class="form_element"><?= $this->element->brands; ?></dd></li>
    <li class=""><dt class=""><label for="websites" class="required">Most Used Sites</label></dt><dd class="form_element"><?= $this->element->websites; ?></dd></li>
    <li class=""><dt class=""><label for="major" class="required">What major are/were you?</label></dt><dd class="form_element"><?= $this->element->major; ?></dd></li>
    <li class=""><dt class=""><label for="career" class="required">What do you do or plan to do for a living?</label></dt><dd class="form_element"><?= $this->element->career; ?></dd></li>
    
    <li class=""><dt class=""><label for="personality" class="required">Describe your personality</label></dt><dd class="form_element"><?= $this->element->personality; ?></dd></li>
    <li class=""><dt  class="form_submit"><?= $this->element->submit; ?></dd></li>
</ul>
</form>