<!--<div id ="view-content">
    
   <?= $this->Errors($this->errors); ?>
<p>

</p>
<p>
  <?= $this->form ?>
    
</p>
</div>-->

<?php $auth = Zend_Auth::getInstance();
        if(!$auth->hasIdentity()){ ?>

<?=$this->DisplayFlashMessages($this->flashMessages); ?>
<div class="out-logo"><h1 class="thelogo"><a class="logo" href="<?= $this->url(array('controller'=>'index','action'=>'index'));?>">PlumeType</a></h1>
 <a href="#" class="signup-button" onclick="Dialog.showDialog({elementSelector:'#reg_ajax_form'});Dialog.doValidate();Dialog.loadLoginData()">Join</a>
</div>

<?php } ?>
<div id="home">
   
    <div class="out-slogan"><h1>Make friends with awesome people 
who share your interests.</h1></div>
    <div class="out-preview">
        <ul>
            <li class="out-one"><img width="250" src="<?php echo $this->baseUrl();?>/images/list-interests.png"/><h3>List your interests.</h3></li>
            
            <li class="out-two"><img width="250" src="<?php echo $this->baseUrl();?>/images/find-events.png" /><h3>Find events near you.</h3></li>
           
            <li class="out-three"><img width="250" src="<?php echo $this->baseUrl();?>/images/meet-people.png" /><h3>Go out and meet cool people.</h3></li>
        </ul>
    </div>
    <div class="out-signup">
       <?= $this->form ?>
      <div class="signup-or">or</div>
        <a href="#" onclick="FBI.authenticate(); Dialog.showDialog({elementSelector:'#fb_ajax_form'})">Facebook Login</a>
</div>

<style type="text/css">
    .right-block {display: none;}
</style>