<!--<div id ="view-content">
    
   <?= $this->Errors($this->errors); ?>
<p>
<?=$this->DisplayFlashMessages($this->flashMessages); ?>
</p>
<p>
  <?= $this->form ?>
    
</p>
</div>-->
<?php $auth = Zend_Auth::getInstance();
        if(!$auth->hasIdentity()){ ?>

<div class="out-logo"><h1 class="thelogo">PlumeType</h1></div>

<?php } ?>
<div id="home">
    
    <div class="out-slogan"><h1>Make friends with awesome people 
who share your interests.</h1></div>
    <div class="out-preview">
        <ul>
            <li class="out-one"><img width="250" src="<?php echo $this->baseURL();?>/images/list-interests.png"/><h3>List your interests.</h3></li>
            
            <li class="out-two"><img width="250" src="<?php echo $this->baseURL();?>/images/find-events.png" /><h3>Find events near you.</h3></li>
           
            <li class="out-three"><img width="250" src="<?php echo $this->baseURL();?>/images/meet-people.png" /><h3>Go out and meet cool people.</h3></li>
        </ul>
    </div>
    <div class="out-signup"><h1><a href="<?php echo $this->baseURL();?>/registration">Get Started</a></h1>
        <h1 class="alternative">Or</h1></div>
    
    <?= $this->form ?>
</div>



<style type="text/css">
    .right-block {display: none;}
</style>