<!--<div id ="view-content">
    
   <?= $this->Errors($this->errors); ?>
<p>

</p>
<p>
  <?= $this->form ?>
    
</p>
</div>-->

<?php $auth = Zend_Auth::getInstance();
        if(!$auth->hasIdentity()){ ?>

<?=$this->DisplayFlashMessages($this->flashMessages); ?>
<div class="out-logo"><h1 class="thelogo"><a class="logo" href="<?= $this->url(array('controller'=>'index','action'=>'index'));?>">PlumeType</a></h1>
<div class="out-signup">
       <?= $this->form ?>
        <a class="facebook-login" href="#" onclick="FBI.authenticate(); ">Login with Facebook</a><a class="reset-password" href="/password-reset">Forgot your password?</a>
        <!--Dialog.showDialog({elementSelector:'#fb_ajax_form'})-->
    </div>
</div>

<?php } ?>
<div id="home">
    <div class="out-preview">
      <h1 class="tagline-top">Make friends.</h1>
         <a href="#" class="signup-button" onclick="Dialog.showDialog({elementSelector:'#reg_ajax_form'});Dialog.doValidate();Dialog.loadLoginData()">
         <!--<img width="960" src="<?php echo $this->baseUrl();?>/images/plumetype-banner.png"/>-->
         </a>    
    </div>
    <div class="homepage-bottom">
      <h1 class="tagline">Meet people who like what you like. Click this image and sign up now.</h1>
    </div>
</div>

<style type="text/css">
    .right-block {display: none;}
</style>
