 <?
 $appId = Zend_Registry::get('config')->siteInformation->appId;
 ?>
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>PlumeType - <?php if ($this->pageTitle) {
                echo $this->pageTitle;
            } else
            {
                echo "Make friends.";
            }; ?></title>
  <?php $this->headLink()          
          ->appendStylesheet($this->baseUrl('css/smoothness/jquery-ui-1.7.3.custom.css'))
          ->appendStylesheet($this->baseUrl('css/autoSuggest.css'))
          ->appendStylesheet($this->baseUrl('css/hermesvy.css'))
          ->appendStylesheet($this->baseUrl('css/hermesv1.css'))
          ->appendStylesheet($this->baseUrl('css/rightblock.css'))
          ->appendStylesheet($this->baseUrl('css/notifications.css'))
          ->appendStylesheet($this->baseUrl('css/jquery.toastmessage.css')) ; ?>
  <?php echo $this->headLink() ?>

  <?php $this->headScript()
          ->appendFile($this->baseUrl('js/jquery/jquery-1.7.2.min.js'))
          ->appendFile($this->baseUrl('js/jquery/js/jquery-ui-1.8.16.custom.min.js'))
          ->appendFile($this->baseUrl('js/jquery.cookie.js'))
          ->appendFile($this->baseUrl('js/ptv1.js'))
          ->appendFile($this->baseUrl('js/jquery.autoSuggest.js'))
          ->appendFile($this->baseUrl('js/jquery.toastmessage.js'))
          ->appendFile($this->baseUrl('js/tags.js'))
          ->appendFile($this->baseUrl('js/jquery.blockUI.js'))
          ->appendFile($this->baseUrl('js/dialog.js'))
          ->appendFile($this->baseURL('js/fb_interface.js'))
          ->appendFile($this->baseURL('js/login.js'))
          ->appendFile($this->baseURL('js/input-text.js'))
          ->appendFile($this->baseURL('js/event.js'))
          ->appendScript("window.appID='{$appId}';window.fbAsyncInit = function() {
                FB.init({
                    appId      : window.appID,
                    status     : true, 
                    cookie     : true,
                    xfbml      : true,
                    oauth      : true
                });
            };
            (function(d){
                var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
                js = d.createElement('script'); js.id = id; js.async = true;
                js.src = '//connect.facebook.net/en_US/all.js';
                d.getElementsByTagName('head')[0].appendChild(js);
            }(document));")
    ?>
  
  <?php echo $this->headScript() ?>