 <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?= $this->pageTitle; ?></title>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl('css/hermesvy.css')); ?>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl('css/hermesv1.css')); ?>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
  <?php echo $this->headScript()->appendFile($this->baseUrl('js/jquery.cookie.js')); ?>
  <?php echo $this->headScript()->appendFile($this->baseUrl('js/ptv1.js')); ?>