<?php 
    $options = array('formName'=>'profileSearch','fieldName' => 'profileSearch_field','viewScriptName'=>'_form_profileSearch.phtml','formAction'=>'/Search/index');
        $form = new Application_Form_Search($options);
        $this->form = $form;
?>
<div id="header_block">
<div id="header_area">
	<div class="page">
                <div id="logo"><a href="<?= $this->url(array('controller'=>'index','action'=>'index'));?>"><h1>PlumeType</h1></a></div>
               <!-- <div id="topmenu">
                    <ul>
                        <li><a href="<?= $this->url(array('controller'=>'profile','action'=>'index'));?>">My Page</a></li>
                        <li><a href="<?= $this->url(array('controller'=>'friend','action'=>'index'));?>">Friends</a></li>
                        <li><a href="<?= $this->url(array('controller'=>'eventCreation','action'=>'index'));?>">Events</a></li>
                        <li><a href="">Another link</a></li>
                    </ul>
                </div>-->	
              <?php $auth = Zend_Auth::getInstance();
        if($auth->hasIdentity()){ echo $this->form; }?>
			<!--<ul id="reg_links">
				<?= $this->Logout(); ?>
                        </ul>-->
				
        </div>
    
        </div>
</div>
