 <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?= $this->pageTitle; ?></title>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl('css/hermesvy.css')); ?>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl('css/hermesv1.css')); ?>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl('css/smoothness/jquery-ui-1.7.3.custom.css')); ?>
  
  <?php echo $this->jQuery()->enable()->uiEnable(); ?>
  <?php echo $this->headScript()->appendFile($this->baseUrl('js/jquery.cookie.js')); ?>
  <?php echo $this->headScript()->appendFile($this->baseUrl('js/ptv1.js')); ?>