<?php 
    $options = array('formName'=>'profileSearch','fieldName' => 'profileSearch_field','viewScriptName'=>'_form_profileSearch.phtml','formAction'=>'/Search/index');
    $form = new Application_Form_Search($options);
    $this->form = $form;
    $identity = Application_Model_UserSettings::hasIdentity();    
?>

<? if($identity){ ?>
<div id="header_block">
	<div id="header_area">
		<div class="page">
                <div id="logo"><a href="<?= $this->url(array('controller'=>'index','action'=>'index'));?>"><h1>PlumeType</h1></a></div>
               	
            <?php  echo $this->form; ?>
			
        </div>
    
   </div>
</div>
<? } ?>

