<?php 
    $userDescription = new Application_Form_PersonalDescription();
    		$this->userDescription = $userDescription;
                
 
?>
<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->render('head.phtml') ?>
</head>
<body>
<div class="custom">
    <?php echo $this->render('header.phtml') ?>
    
 	<div id="content_area">
 		<div class="page">     
                   
                    <?php echo $this->layout()->content ?>
                    <?php $auth = Zend_Auth::getInstance(); 
                    if($auth->hasIdentity()){ ?>
                    <div class="right-block">
                        <div class="create_button">
                            <a href="eventCreation"><h1>Create Event</h1></a>
                        </div>
                        <div class="block-item upcoming_events">
                            <div class="block-header">
                                <h3>Upcoming Events</h3>
                                 </div>
                                <div class="block-body">
                                <?= $this->DisplayEventFeed($this->identity); ?>
                                </div>
                           
                        </div>
                        <div class="block-item friends_list">
                           <div class="block-header">
                            <h3>Friends</h3>
                            </div>
                            <div class="block-body">
                            <?= $this->DisplayFriends($this->identity) ?>
                            </div>
                           
                          </div>
                        
                        <div class="block-item quick_profile">
                            <div class="block-header">
                            <h3>Edit Bio</h3>
                            </div>
                            <div class="block-body" style="overflow: hidden;">
                            <?= $this->userDescription ?>
                            </div>
                            

                        </div>
                    </div>
                   <?php } ?>
		</div>
	</div>	

       <?php echo $this->render('footer.phtml') ?>
    </div>
</body>
</html>