<?php 
    $userDescription = new Application_Form_PersonalDescription();
    		$this->userDescription = $userDescription;
              $event = new Application_Form_CreateEvent();    
            $reg = new Application_Form_Registration();
 
?>
<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <?php echo $this->render('head.phtml') ?>
</head>
<body class="<?= $this->LayoutClass() ?>">

<div class="custom<?php $auth = Zend_Auth::getInstance();
        if(!$auth->hasIdentity()){ echo ' outside'; }?>">
    <?php echo $this->render('header.phtml') ?>
    
 	<div id="content_area">
 		<div class="page">     
                   
                    <?php echo $this->layout()->content ?>
                    <?php $auth = Zend_Auth::getInstance(); 
                    if($auth->hasIdentity()){ 
                    	$this->identity = $auth->getIdentity()?>
                    <div class="right-block">
                        <div class="create_button">
                            <a href="#" onclick="Dialog.showDialog({elementSelector:'#event_ajax_form',func:Dialog.loadEventDatePicker})"><h1>Create Event</h1></a>
                        </div>
                        
                         <div class="block-item upcoming_events">
                            <div class="block-header">
                                <h3>Upcoming Events</h3>
                                 </div>
                                <div class="block-body">
                                <?= $this->DisplayEventFeed($this->identity, 5); ?>
                                </div>
                           
                        </div>
                        <div class="block-item friends_block">
                            <div class="block-header">
                                <h3>Friends</h3>
                                 </div>
                                <div class="block-body">
									
                                <?= $this->DisplayFriends($this->identity); ?>
                                </div>
                           
                        </div>

                        </div>
                    </div>
                     <!-- Dialog Stuff -->
					<div class = "footer_ajax" style="display:none">
						<div id="event_ajax_form">	
							<?=$event?>
						</div>
						<div class ="modalWindow">
						</div>
				    
					</div>
					<div class = "modalBackground" style="display:none;"></div>
					<div class ="dialogs"></div>	
                                        
                 

	<? } ?>
			</div>
	</div>
       <?php
	if(!$auth->hasIdentity()){ ?>
	<div class = "footer_ajax" style="display:none">
						<div id="reg_ajax_form">	
							<?= $reg ?>
						</div>
						<div class ="modalWindow">
                                                    
						</div>	
					</div>
					<div class = "modalBackground" style="display:none;"></div>
					<div class = 'dialogs' style="display:none">
					</div>
	</div>		
    <?}
     echo $this->render('footer.phtml');?>     

   

</body>
</html>