<?php 
    $userDescription = new Application_Form_PersonalDescription();
    		$this->userDescription = $userDescription;
              $event = new Application_Form_CreateEvent();    
            $reg = new Application_Form_Registration();
	    
    $identity = Application_Model_UserSettings::hasIdentity();
    $appId = Zend_Registry::get('config')->siteInformation->appId;
 
?>
<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php echo $this->render('head.phtml') ?>
</head>
<body class="<?= $this->LayoutClass() ?>">
<div id="fb-root"></div>




<div class="custom<?php 
        if(!$identity){ echo ' outside'; }?>">
    <?php echo $this->render('header.phtml') ?>
    
 	<div id="content_area">
 		<div class="page">     
                   
		    <div class="main_ajax_content">
			<?php echo $this->layout()->content ?>
		    </div>
                    <?php 
                    if($identity){ 
                    	?>
                    <div class="right-block">
                        <div class="create_button">
                            <a href="#" onclick="Dialog.showDialog({elementSelector:'#event_ajax_form',func:Dialog.loadEventDatePicker})"><h1>Create Event</h1></a>
                        </div>
                        
                         <div class="block-item upcoming_events">
                            <div class="block-header">
                                <h4>Upcoming Events</h4>
                                 </div>
                                <div class="block-body">
                                <?= $this->DisplayEventFeed($identity, 5); ?>
                                </div>
                           
                        </div>
                        <div class="block-item friends_block">
                            <div class="block-header">
                                <h4>Friends</h4>
                                 </div>
                                <div class="block-body">
									
                                <?= $this->DisplayFriends($identity); ?>
                                </div>
                           
                        </div>

                        </div>
                    </div>
                     <!-- Dialog Stuff -->
					<div class = "footer_ajax" style="display:none">
						<div id="event_ajax_form">	
							<?=$event?>
						</div>
						<div class ="modalWindow">
						</div>
				    
					</div>
					<div class = "modalBackground" style="display:none;"></div>
					<div class ="dialogs"></div>	
                                        
                 

	<? } ?>
			</div>
	</div>
       <?php
	if(!$identity){ ?>
	<div class = "footer_ajax" style="display:none">
						<div id="reg_ajax_form">	
							<?= $reg ?>
						</div>
						<div class ="modalWindow">
                                                    
						</div>	
					</div>
					<div class = "modalBackground" style="display:none;"></div>
					<div class = 'dialogs' style="display:none">
					</div>
	</div>		
    <?}
     echo $this->render('footer.phtml');?>     

   

</body>
</html>