<?php 
    $userDescription = new Application_Form_PersonalDescription();
    		$this->userDescription = $userDescription;
              $event = new Application_Form_CreateEvent();    
            $reg = new Application_Form_Registration();
			
    $identity = Application_Model_UserSettings::hasIdentity();

?>
<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?php echo $this->render('head.phtml') ?>
	</head>
	<body class="<?= $this->LayoutClass() ?>">
	<div id="fb-root"></div>
	<div class="signup-transparency" onclick="Dialog.showDialog({elementSelector:'#reg_ajax_form'});Dialog.doValidate();Dialog.loadLoginData()"></div>
	<div class="custom outside">
		<div id="content_area">
			<div class="page">     
					   
				<div class="main_ajax_content">
				<?php echo $this->layout()->content ?>
				</div>
					
			</div>
		</div>
		
		<div class = "footer_ajax" style="display:none">
			<div id="reg_ajax_form">	
				<?= $reg ?>
			</div>
			<div class ="modalWindow"></div>	
		</div>
		<div class = "modalBackground" style="display:none;"></div>
			<div class = 'dialogs' style="display:none"></div>
		<?= $this->render('footer.phtml');?>
	</div>		
		     
	</body>
</html>