<?php
	$stringInjection = "Thank you for registering with PlumeType. Please confirm your email with us by clicking on the link below. When you're done with that, 
						you'll be able to start searching for cool people to hang out with. Awesome.<br/>
						<a href = ".$this->inputs['activationUrl'].
						$this->url(array('controller'=>'account','action'=>'confirm','key'=>$this->inputs['activationCode'])).
                   		"Click to Confirm Registration</a><br/><br/>";
?>
<?= $this->partial('emailTemplate.phtml', array('name'=>$this->inputs['name'], '$stringInjection'=>$stringInjection))?>
	