<table style="background: #454545;">
    <tr><td>
    
    <table cellpadding="0" cellspacing="0" style=" width: 700px; margin: 0 auto; border-radius: 5px; background: #ddd;">
        <tr>
        <td >
            <a style="margin: 5px; float:left; width: 240px;" href="http://plumetype.com">
                <img style=" width: 240px; height: 55px" src="http://plumetype.com/images/plumetype-flat.png" />
            </a>
        </td>
    </tr>
    <tr>
        <td>
		<p style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;
					background: #eee; padding: 10px 10px 30px 30px; 
					border-bottom-right-radius: 5px; 
					border-bottom-left-radius: 5px;
					min-height: 300px;
                                        margin: 0px;">
		<span style="font-size: 14px">Your friend <?= $this->inputs['yourName'] ?> has created a new event.</span> 
		<br /><br/>
        <h2>Event Information</h2></h3>
        <h3>Friend: <?= $this->inputs['name'] ?></h3>
        <h3>Location: <?= $this->inputs['location'] ?></h3>
        <h3>Date: <?= $this->inputs['date'] ?></h3>
        <h3>Private: <?= $this->inputs['private'] ?></h3>
        
		Join your friends events!
        
                <br/><br/>
                Sincerely,
                    <br />
                PlumeType
	        
        </p>
        </td>
    </tr>
      
    </table>
    
    </td></tr>
</table>