<table style="background: #454545;">
    <tr><td>
    
    <table cellpadding="0" cellspacing="0" style=" width: 700px; margin: 0 auto; border-radius: 5px; background: #ddd;">
        <tr>
        <td >
            <a style="margin: 5px; float:left; width: 204px;" href="http://plumetype.com">
                <img style=" width: 204px;" src="http://plumetype.com/images/plumetype-flat.png" />
            </a>
        </td>
    </tr>
    <tr>
        <td>
		<p style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;
					background: #eee; padding: 10px; 
					border-bottom-right-radius: 5px; 
					border-bottom-left-radius: 5px;
					min-height: 300px;
                                        margin: 0px;">
		<span style="font-size: 14px">Hi <?= $this->inputs['name'] ?>,</span> 
		<br /><br/>
		<!--Click on the link below to reset your Plumetype password.-->
        <p>Here is your temporary password: <?= $this->inputs['password'] ?></p>
        
                <br/>
                
                <!--<a href = "<?= $this->inputs['activationUrl'].
					$this->url(array('controller'=>'account',
						'action'=>'confirm',
						'key'=>$this->inputs['activationCode']))?>">
                   			Reset Password ></a>-->
                <br/><br/>
                <hr />
                <br/>
                Have issues or questions? Email us at support@plumetype.com.
                <br/>
                Sincerely,
                    <br />
                PlumeType
	        
        </p>
        </td>
    </tr>
      
    </table>
    
    </td></tr>
</table>