<table style="background: #FFFFFF;">
    <tr><td>
    
    <table cellpadding="0" cellspacing="0" style=" width: 700px; margin: 0 auto;">
        <tr>
        <td >
            <a style="float:left; width: 240px;" href="http://plumetype.com">
                <img style="width: 240px; height: 55px" src="http://plumetype.com/images/plumetype-flat.png" />
            </a>
        </td>
    </tr>
    <tr>
        <td>
		<p style="font-family: 'myriad pro', Arial, Helvetica Neue, Helvetica, sans-serif: 12px;
					background: #FFFFFF;
                                        margin-top: 10px;">
                <span style="margin: 20 0 0 0px;">Hi <?= $this->inputs['name'] ?>,</span>
                <br />
		<span style="margin: 0 0 0 0px;">Your friend <span style="color:#FF8600";><?= $this->inputs['yourName'] ?></span> has created a new <span style="color:#FF8600";><?= $this->inputs['private'] ?></span> event:</span>
                <br />
        <h4 style="padding: 0px; margin: 0 0 5 0px; color: #000000 !important;">Event: <?= $this->inputs['shortDescription'] ?></h4>
        <h4 style="padding: 0px; margin: 0 0 5 0px; color: #000000 !important;">Location: <?= $this->inputs['location'] ?></h4>
        <h4 style="padding: 0px; margin: 0 0 5 0px; color: #000000 !important;">Date: <?= $this->inputs['date'] ?></h4>
        <br />
		Click here for more details.
        
                <br /><br />
                Sincerely,
                    <br />
                PlumeType
	        
        </p>
        </td>
    </tr>
    <table cellpadding="0" cellspacing="0" style="width: 700px; height: 50px; margin: 0 auto; background: #000000; margin-top: 20px">
    <tbody>
    <tr>
        <td>
        <h4 style="color: #FFFFFF !important; text-align: center; margin-top: 20px;">PlumeType.com - Make friends.</h4>
        </td>
    </tr>
    </tbody>
    </table>
    </table>
    
    </td></tr>
</table>