<div id="view-content">
    <div class="view-wrapped">	 
        <div class="event_header">
        <h1 class="event_title"><?= $this->event->getCreator->getFirstName." Wants to ".$this->event->getShortDescription() ?></h1>
        <h2 class="event_self">Event Public Page - <a class='' href = '/event/request/eid/{$event->result->getEid()}'>I'm down</a></h2>
		
        </div>
        <div class="event_main">
            <div class="event_img">
                <img src="/img/profile-pic/uid/<?=$this->identity ?>" height=200  width=200/>
            </div>
            <div class="event_right">
            <div class='event_date'>
                <h2><?= date('F j\, Y',$this->event->getDate()->getTimestamp()); ?></h2>
            </div>	
           
            </div>
        </div>
	
</div>
</div>