<br /><br />
<div id="view-content">
<b>Event Creator Page</b>	 
<?= $this->event->getCreator->getFirstName." Wants to ".$this->event->getShortDescription() ?>
<br />
<p>
	<div class='longDescription'>
		<?= $this->event->getLongDescription() ?>
</div>	
<p>
	<div class='interested_list'>
		<?= $this->DisplayInterestedList($this->event) ?>
	</div>
 <div class = 'wall'>
 	Wall <br />
		<?= $this->DisplayEventWall($this->event,$this->identity) ?>
 </div>	
	
</div>