<div id="view-content">
    <div class="view-wrapped">	 
        <div class="event_main">
	    <h2 class="event_title"><?= $this->creatorName ." wants to ".$this->event->getShortDescription() ?></h2>
            <div class="event-left">
	    <div class="event_img">
                <img src="/img/profile-pic/uid/<?=$this->identity ?>" height=180  width=180/>
	    </div>
	    	    <div class="event_self">Public Event</div>
	    	    <? if(!$this->didRequest) {?>
		    <a class='attend-button' href = '/event/request/eid/<?= $this->eid; ?>'>I wanna go!</a>
		<? } ?>
	    </div>
            <div class="event_right">
            <div class='event_date'>
                <h4><?= date('F j\, Y',$this->event->getDate()->getTimestamp()); ?></h4>
            </div>
            </div>
	
</div>
</div>