<?php
$this->headScript()->appendFile($this->baseUrl('js/wall.js'));
$eid = $this->event->getEid();
?>
	<?= $this->partial('eventInfo.phtml',array('event'=>$this->event,'identity'=>$this->identity, 'indexCreator'=>$this->indexCreator, 'isEventExpired'=>$this->isEventExpired, 'didRequest'=>$this->didRequest, 'curUser'=>$this->curUser)); ?>
	
	
 
	
</div>
</div>
<?= $this->inlineScript()->appendScript("$(document).ready(Wall.refreshWall({eid:'{$eid}'}));");?>