<div id="view-content">
    <div class="view-wrapped">	 
        <div class="event_header">
        <h1 class="event_title"><?= $this->event->getCreator->getFirstName." Wants to ".$this->event->getShortDescription() ?></h1>
        </div>
        <div class="event_main">
            <div class="event_img">
                <img src="/img/profile-pic/uid/<?=$this->identity ?>" height=180  width=180/>
				<? if(!$this->didRequest) {?>
		    <div class="attend-button"><a class='remove-anchor' href = '/event/request/eid/<?= $this->eid; ?>'>I wanna go!</a></div>
		<? } ?>
            </div>
            <div class="event_right">
		        <h2 class="event_self">Public Event</h2>
            <div class='event_date'>
                <h2><?= date('F j\, Y',$this->event->getDate()->getTimestamp()); ?></h2>
            </div>	
            </div>
        </div>
	
</div>
</div>