<!--<div class="loginonce"><?= $this->message; ?><div class="exitbutton"></div></div>-->
<?//= $this->firstname; ?> <?//= $this->lastname; ?>
<? 
	$interestModel = new Application_Model_InterestModel($this->user->getInterest());
	$tagArray = $interestModel->getTags();
	$this->headScript()->appendFile($this->baseUrl('js/questions.js'))
?>
<script src="../js/tags.js"></script>

<div id="view-content">	
    <div class="view-wrapped">
      
  <div class="top_col">
			<center><?=$this->DisplayFlashMessages($this->flashMessages); ?></center>
			<center><?=$this->DisplayNewUserflow($this->flowStatus); ?></center>
			<?= $this->partial('tags.phtml',array('tagArray'=>$tagArray,'interestModel'=>$interestModel,'isOwn'=>true)) ?>
		<div class = tag_dropdown onclick = "Tags.toggleDropDown();">
			Add a tag
		</div>
		    <div class = tag_input_wrapper style="">
			<input type="text" class ="tag_input"></input>
  </div>
		</div>
        <a href="#" onclick="cats.getCurrentCat()" >hifdsjaklfds;la</a>
           
	  <?= $this->catTag; ?>
    </div>
</div>

<div class = "ajax_content" style = "display:none">
	<div class = "tags_base ajax"></div>
	<div class = "ajax_tags_wrap">
		<div class ="tags" id="tag_" onclick = ''>
			<div class="tag_text"></div>
			<div class="close_tag" onclick=""></div>
		</div>		
	</div>	
</div>

<script type="text/javascript" >
	
     var loadFeeds = function(identity){
		$("#main_feed").html('<img src="/images/loading.gif" alt=""/>');
 		$.ajax({
			url:"/ajax/load-feed/identity/"+identity,
			context:document.body,
			success:function(data){
				$("#main_feed").html(data);
			}

		});
     }   
 </script>    

<?= $this->inlineScript()->appendScript("$(document).ready(Tags.init());");?>
