<!--<div class="loginonce"><?= $this->message; ?><div class="exitbutton"></div></div>-->
<?//= $this->firstname; ?> <?//= $this->lastname; ?>
<? 
	$interestModel = new Application_Model_InterestModel($this->user->getInterest());
	$tagArray = $interestModel->getTags();
?>
<script src="../js/tags.js"></script>

<div id="view-content">	
    <div class="view-wrapped">
    <div class="top_col">
		
		<? //=$this->DisplayTags($this->user->getInterest()) ?>
		<? //=$this->tagForm; ?>
		  <div class="tags_area">
		 	 <div class="tags_base">
				<? if(count($tagArray) > 0){ 
						foreach($tagArray as $tag){ ?>
							<div class ="tags" id="tag_<?=$tag->getTagName()?>" onclick = 'Tags.toggleTag("tag_<?=$tag->getTagName()?>")'>
								<div class="tag_text"><?=$tag->getTagName()?></div>
								<div class="close_tag" onclick="Tags.removeTag('tag_<?=$tag->getTagName()?>')"></div>
							</div>				
				<?			
						}
				}				
				?>		  
		  	</div>
		  </div>
		<div class = tag_dropdown onclick = "Tags.toggleDropDown();">
			Add a tag
		</div>
		<div class = tag_input_wrapper style="display:none;">
			<input type="text" class ="tag_input"></input>
		</div>
		<!--  <img src="/img/profile-pic" height=100  width=100/>  USE THIS FOR PROFILE PICS-->
    </div>
             
	<div class="left_col">
		<h2>Feed</h2>
		<div id = "main_feed">
			<?= $this->DisplayGeneralFeed($this->identity); ?>
         </div>      
		<a href = "#" onclick = "loadFeeds('<?= $this->identity ?>')">Refresh Feed</a>
	</div>
        <div class="right_col">
		<?=$this->DisplayNewUserFlow($this->flowStatus)?>
		
		<h2>Upcoming Events</h2>
			<?= $this->DisplayEventFeed($this->identity); ?>	
        </div>
    </div>
</div>

<div class = "ajax_content" style = "display:none">
	<div class = "tags_base ajax"></div>
	<div class ="tags" id="tag_" onclick = 'Tags.toggleTag("")'>
		<div class="tag_text"></div>
		<div class="close_tag" onclick="Tags.removeTag('')"></div>
	</div>		
</div>

<script type="text/javascript">
     var loadFeeds = function(identity){
		$("#main_feed").html('<img src="/images/loading.gif" alt=""/>');
 		$.ajax({
			url:"/ajax/load-feed/identity/"+identity,
			context:document.body,
			success:function(data){
				$("#main_feed").html(data);
			}

		});
     }   
</script>
<?= $this->inlineScript()->appendScript("$(document).ready(Tags.init());");?>
