<br /><br />
<div id="view-content">
	<p>View script for controller <b>Profile</b> and script/action name <b>index</b></p>
	<?= $this->message; ?>
	<?= $this->form; ?>
	<?=$this->identity?>
	<p> <a href = " <?= $this->url(array('controller'=>'eventCreation','action'=>'index')) ?>">Create Event Test</a></p>
	<p><a href = "<?= $this->url(array('controller'=>'friend','action'=>'index')) ?>"> Add a friend</a></p>
	<p>
		<b>Feed</b>
		<?= $this->DisplayGeneralFeed($this->identity); ?>
	</p>
	<p>
		<b>Upcoming Events</b>
		<?= $this->DisplayEventFeed($this->identity); ?>
	</p>
</div>