<?php
$interestModel = new Application_Model_InterestModel($this->user->getInterest());
$tagArray = $interestModel->getTags();
$gender = ($this->user->getGender() == 'n') ? '':($this->user->getGender().',');

?>
<div id="view-content">
        <div class="view-wrapped">
            <div class="profile_header">
                <h1 class="big_name"><?= $this->name; ?>.</h1>
						
                <? if (!$this->isFriend && !$this->createdFriendRequest){?>
                             <div class = "friendStatus">
                                <a class="remove-anchor" href ="/friend/friendRequest/requestee/<?= $this->email; ?>">
                                    Add
                                </a>
                            </div>
                  <? }?>
            </div>
            <div class ="user_details">
                <h2><?=$gender?> <?=$this->user->getCity()?></h2>
            </div>
            <div class="profile_leftCol">
            <div class="profile_image">
                <img src="/img/profile-pic/uid/<?=$this->user->getEmail();?>" height="100" width="100" />
            </div>
            <div class="profile_eventList">
                <?= $this->DisplayEventFeed($this->user->getEmail(), 4); ?>        
            </div>
            </div>
            <div class="profile_rightCol">
                <div class="profileDesc">
                    <? if($this->description)
								echo $this->description;
						else
								echo "No description available";?>
            </div>
                <div class="profile_tags">
                    <h2>Tags</h2>
     			<?= $this->partial('tags.phtml',array('tagArray'=>$tagArray,'interestModel'=>$interestModel)) ?>
		</div>
		  </div>
                </div>
                
            </div>
            
            
     
