<?php
$interestModel = new Application_Model_InterestModel($this->user->getInterest());
$tagArray = $interestModel->getTags();
$gender = ($this->user->getGender() == 'n') ? '':($this->user->getGender().',');

?>
<div id="view-content">
        <div class="view-wrapped">
            <div class="profile_leftCol">
            <div class="profile_image">
                <img src="/img/profile-pic/uid/<?=$this->user->getUid();?>" height="180" width="180" />
            </div>
	    <div class="profile-events-header"><h4>Events</h4></div>
            <div class="profile_eventList">
                <?= $this->DisplayEventFeed($this->user->getEmail(), 4); ?>        
            </div>
            </div>
            <div class="profile_rightCol">
		<div class="profile_header">
                <h1 class="big_name"><?= $this->name; ?></h1>
                <? if (!$this->isFriend && $this->createdFriendRequest){?>
                                <a class="add-friend" href ="/friend/friendRequest/requestee/<?= $this->user->getUid(); ?>">Add friend</a>
                  <? }?>
		<div class ="user_details">
                <h3><?=$gender?> <?=$this->user->getCity()?></h3>
            </div>
            </div>
		<div class="profileWrapper">
                <div class="profileDesc"><h4>About me</h4>
                    <div class="profile-about-me"><? if($this->description)
								echo $this->description;
						else
								echo "<h4>No description available</h4>";?>
		    </div>
		    </div>
		</div>
		<div class="profileTagWrapper">
                <div class="profile_tags">
                    <h4>Tags</h4>
     			<?= $this->partial('tags.phtml',array('tagArray'=>$tagArray,'interestModel'=>$interestModel)) ?>
		</div>
		</div>
		  </div>
                </div>
                
            </div>
            
            
     
