<?php $auth = Zend_Auth::getInstance();
        if(!$auth->hasIdentity()){ ?>

<div class="out-logo"><h1 class="thelogo">PlumeType</h1></div>

<?php } else { ?>
<h1 class="cms-title">Contact Us</h1>
<?php } ?>
    <?= $this->Errors($this->errors); ?>
    <p>
        <?=$this->DisplayFlashMessages($this->flashMessages); ?>
    </p>
    <div class="cms-page">
        <div class="cms-text">
        <p>Site not working? Have any questions? Want to learn more about PlumeType? Fill in the contact form below and we'll get back to you ASAP. We're also open to chat about pretty much anything, so feel free to just drop in and say hi!</p>
         <?= $this->form ?>
        </div></div>
<script type="text/javascript">
    $('.out-logo').prepend('<h1 class="prepend-logo">Contact</h1>');
   
</script>
<style type="text/css">
    .right-block {display: none;}
</style>