    <?= $this->Errors($this->errors); ?>
	
    <p>
        <?=$this->DisplayFlashMessages($this->flashMessages); ?>
    </p>
    <div class="cms-page">
        <div class="cms-text">
         <?= $this->form ?>
	<div class="password-change-text">
	    If you can't remember your password, use <a href='/password-reset'>this form</a>. If you still can't login, or have other account issues,
	    send us an email at contact@plumetype.com.
	</div>
        </div></div>
<script type="text/javascript">
   
</script>
<style type="text/css">
    .right-block {display: none;}
</style>