<?php $auth = Zend_Auth::getInstance();
        if(!$auth->hasIdentity()){ ?>

<div class="out-logo"><h1 class="thelogo"><a href="<?= $this->url(array('controller'=>'index','action'=>'index'));?>">PlumeType</a></h1></div>

<?php } else { ?>
<h1 class="cms-title">Register</h1>
<?php } ?>

<?= $this->Errors($this->errors); ?>
  <div class="cms-page">
        <div class="cms-text">
<?= $this->form; ?>	
<br /> 
<?= $this->successMessage; ?>
        </div>
  </div>
<style type="text/css">
    .right-block {display: none;}
</style>