<?php $auth = Zend_Auth::getInstance();
        if(!$auth->hasIdentity()){ ?>

<div class="out-logo"><h1 class="thelogo"><a class="logo" href="<?= $this->url(array('controller'=>'index','action'=>'index'));?>">PlumeType</a></h1></div>
<h1 class="cms-title">Reset Your Password</h1>
<?php } ?>
    <?= $this->Errors($this->errors); ?>
    <p>
        <?=$this->DisplayFlashMessages($this->flashMessages); ?>
    </p>
    <div class="cms-page">
        <div class="cms-text">
         <?= $this->form ?>
        </div></div>
<script type="text/javascript">
   
</script>
<style type="text/css">
    .right-block {display: none;}
</style>